stages:
    - build
    - build-unity-plugin

.build-base:
    image: registry.videolan.org/vlc-debian-llvm-mingw:20200603153044
    tags:
        - docker
        - amd64
    stage: build
    script:
        - git clone https://code.videolan.org/videolan/vlc/ && cd vlc && extras/package/win32/build.sh $ARGS 
    after_script:
        - mkdir nightlies
        - ls ./vlc/win64
        - cp ./vlc/win64/$ARTIFACT nightlies
    artifacts:
        paths:
            - nightlies/*
        expire_in: 2 weeks

libvlc-x86_64-debug:
    extends: .build-base
    variables:
        ARGS: -c -d -x -l -i n -a x86_64
        ARTIFACT: vlc-4.0.0-dev-win64-debug.7z
        
libvlc-x86_64:
    extends: .build-base
    variables:
        ARGS: -c -r -x -l -i n -a x86_64
        ARTIFACT: vlc-4.0.0-dev-win64.7z

libvlcsharp-unity:
    tags:
        - docker
        - amd64
    stage: build
    script:
        - wget https://download.visualstudio.microsoft.com/download/pr/0c795076-b679-457e-8267-f9dd20a8ca28/02446ea777b6f5a5478cd3244d8ed65b/dotnet-sdk-3.1.300-linux-x64.tar.gz
        - mkdir -p $HOME/dotnet && tar zxf dotnet-sdk-3.1.300-linux-x64.tar.gz -C $HOME/dotnet
        - export DOTNET_ROOT=$HOME/dotnet
        - export PATH=$PATH:$HOME/dotnet
        - dotnet --version
        - mkdir tmp && cd tmp && git clone https://code.videolan.org/videolan/LibVLCSharp lvs
        - cd lvs
        - git checkout -f -B master
        - git apply buildsystem/linux.patch
        - dotnet build src/LibVLCSharp/LibVLCSharp.csproj /p:UNITY=true -c Release
    after_script:
        - mkdir nightlies
        - cp tmp/lvs/src/LibVLCSharp/bin/Release/netstandard2.0/LibVLCSharp.dll nightlies
    artifacts:
        paths:
            - nightlies/*
        expire_in: 2 weeks

unity-plugin:
    image: registry.videolan.org/vlc-debian-llvm-mingw:20200603153044
    dependencies: 
        - libvlc-x86_64
    tags:
        - docker
        - amd64
    stage: build-unity-plugin
    script:
        - 7z x ./nightlies/vlc-4.0.0-dev-win64.7z -o./build
        - mkdir -p Assets/VLCUnity/Plugins/x86_64
        - cp -R ./build/vlc-4.0.0-dev/{libvlc.dll,libvlccore.dll,hrtfs,locale,lua,plugins} Assets/VLCUnity/Plugins/x86_64
        - rm -rf Assets/VLCUnity/Plugins/x86_64/lua/http
        - cp -r ./build/vlc-4.0.0-dev/sdk/ PluginSource/
        - ./build.sh